# Generated by Django 3.0.5 on 2021-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
