# Generated by Django 3.0.5 on 2021-05-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USER',
        ),
    ]
