# Generated by Django 3.0.5 on 2021-05-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20210528_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='is_verified',
        ),
    ]
